### ISSUE TITLE
예빈이 사용자이름 설정 

### ISSUE THREAD

**Issue by jihye14** [eunhyuneeee/SWE_#12]
![default](https://cloud.githubusercontent.com/assets/15049592/10862021/27b195d6-7fdb-11e5-9f20-8878d7cbaee2.JPG)

예빈이 사용자 이름이 왜 studentInfoSystem??? git log해보니까 이럼

**Comment by yebbiii** [comment]
바꿨음당~~~
바꾸는방법: eclipse에서 window-preference-team-git-configuration에서 name바꾸면 됨
